### ISSUE TITLE
Job cannot be started

### ISSUE THREAD

**Issue by Farazashtiani** [clemsonciti/palmetto-documentation#1]
During past 4 days I have not been able to start a job. When I request an interactive job, it tries to start it but it takes forever. The last line is "qsub: waiting for job .......... to start." My requested interactive job (which I have been using during the past month) is as bellow:
qsub -I -l select=1:ncpus=36:mem=700gb,walltime=10:00:00 -q bigmem

Best,
Faraz

**Comment by shwina** [comment]
Faraz, I am closing this issue as this repository is not for reporting issues using the cluster. Please e-mail ithelp@clemson.edu including the word "Palmetto" in the subject line with your request.
