### ISSUE TITLE
Gpu Warning

### ISSUE THREAD

**Issue by srihithalwala** [clemsonciti/palmetto-documentation#2]
Hello, I am working on pytorch image-classifier models and I am getting the following warning 

Warning: Found GPU0 Tesla M2075 which is of cuda capability 2.0.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
/home/salwala/.conda/envs/tf/lib/python3.6/site-packages/torch/cuda/__init__.py:117: UserWarning: 
    Found GPU1 Tesla M2075 which is of cuda capability 2.0.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))

Error:
RuntimeError: cuDNN error: CUDNN_STATUS_ARCH_MISMATCH.

Please help

-

**Comment by shwina** [comment]
@srihithalwala 

Are you accessing Palmetto's compute resources via JupyterHub, or via `qsub`? If you are using JupyterHub, currently, the best way to get a better GPU is to ask for at least 20 CPU cores.

If you are using `qsub`, you can follow the instructions here to specify the type of GPU you need:

https://www.palmetto.clemson.edu/palmetto/userguide_howto_use_gpus.html

**Comment by srihithalwala** [comment]
Thank you
